#version 450

layout (local_size_x = 16, local_size_y = 16) in;
layout (binding = 0, r8) uniform readonly image2D inTex;
layout (binding = 1, rgba32f) uniform image2D outTex;

void main(){
    ivec2 uv = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(inTex);
    if(uv.x >= size.x || uv.y >= size.y){
        return;
    }
    float alpha = imageLoad(inTex,uv).r;     
    imageStore(outTex,uv,vec4(alpha)); 
}