#version 450

layout (local_size_x = 16, local_size_y = 16) in;
layout (binding = 0) buffer inBuffer{
    float dataIn[];
};
layout (binding = 1, r8) uniform image2D outTex;

void main(){
    ivec2 uv = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(outTex);
    if(uv.x >= size.x || uv.y >= size.y){
        return;
    } 
    float vaule = dataIn[uv.y*size.x + uv.x];
    imageStore(outTex,uv,vec4(vaule));  
}

